export const jobs = [
  {
    id: "1",
    companyName: "NovaTech Solutions",
    title: "DataOps Engineer (m/f/d)",
    seniorityLevel: "Senior",
    employmentType: "Full time",
    location: "Berlin",
    mustHaveSkills: [
      "Test automation",
      "IaC (infrastructure as code)",
      "Containerization",
      "Data modeling",
      "Scripting (Bash/Python/Go/Ruby)",
      "Python",
      "CI/CD Pipelines (e.g. Github Actions)",
      "Cloud knowledge",
      "Monitoring",
    ],
    niceToHaveSkills: [
      "Agile Methodologies",
      "Software Development",
      "Java",
      "German language skills",
      "Project Management",
      "B2B",
      "Kafka",
      "Redshift",
      "Golang",
    ],
    annualSalary: "€ 75K - 95K",
    howToApply: "test@test.de",
  },
  {
    id: "2",
    companyName: "NovaTech Solutions",
    title: "Machine Learning Engineer (m/f/d)",
    seniorityLevel: "Mid",
    location: "Berlin",
    employmentType: "Full time",
    annualSalary: "€ 55K - 75K",
    mustHaveSkills: [
      "Python",
      "CI/CD (e.g. Azure Devops/Github Actions)",
      "Tensorflow",
      "Spark",
      "Cloud (Azure/AWS)",
      "Training machine learning models",
      "IaC",
    ],
    niceToHaveSkills: [
      "Monitoring",
      "Golang",
      "Kubernetes",
      "Communication skills",
      "Agile Methodologies",
      "Airflow",
      "C/C++",
    ],
    howToApply: "test@test.de",
  },
  {
    id: "3",
    companyName: "NovaTech Solutions",
    title: "Security Engineer (m/f/d)",
    seniorityLevel: "Mid",
    location: "Berlin",
    employmentType: "Full time",
    annualSalary: "€ 55K - 75K",
    mustHaveSkills: [
      "Software security",
      "Threat modelling",
      "Security by design",
      "Python",
      "Cloud(azure / aws)",
      "C#",
    ],
    niceToHaveSkills: [
      "German language skills",
      "Digital forensics",
      "C++",
      "Java",
    ],
    howToApply: "test@test.de",
  },
];
