export const skills = [
  { value: "javascript", label: "JavaScript" },
  { value: "python", label: "Python" },
  { value: "react", label: "React" },
  { value: "java", label: "Java" },
  { value: "html", label: "HTML" },
  { value: "css", label: "CSS" },
  { value: "sql", label: "SQL" },
  { value: "nodejs", label: "Node.js" },
  { value: "angular", label: "Angular" },
  { value: "vuejs", label: "Vue.js" },
  { value: "csharp", label: "C#" },
  { value: "php", label: "PHP" },
  { value: "ruby", label: "Ruby" },
  { value: "swift", label: "Swift" },
  { value: "kotlin", label: "Kotlin" },
  { value: "typescript", label: "TypeScript" },
  { value: "flutter", label: "Flutter" },
  { value: "django", label: "Django" },
  { value: "spring", label: "Spring Framework" },
  { value: "mongodb", label: "MongoDB" },
  { value: "mysql", label: "MySQL" },
  { value: "postgresql", label: "PostgreSQL" },
  { value: "aws", label: "Amazon Web Services (AWS)" },
  { value: "azure", label: "Microsoft Azure" },
  { value: "gcp", label: "Google Cloud Platform (GCP)" },
  { value: "docker", label: "Docker" },
  { value: "kubernetes", label: "Kubernetes" },
  { value: "git", label: "Git" },
  { value: "jenkins", label: "Jenkins" },
  { value: "redux", label: "Redux" },
  { value: "webpack", label: "Webpack" },
  { value: "sass", label: "Sass" },
  { value: "less", label: "Less" },
  { value: "rust", label: "Rust" },
  { value: "scala", label: "Scala" },
  { value: "go", label: "Go (Golang)" },
  { value: "hadoop", label: "Hadoop" },
  { value: "spark", label: "Apache Spark" },
  { value: "tensorflow", label: "TensorFlow" },
  { value: "pytorch", label: "PyTorch" },
  { value: "machinelearning", label: "Machine Learning" },
  { value: "datascience", label: "Data Science" },
  { value: "cybersecurity", label: "Cybersecurity" },
  { value: "networking", label: "Networking" },
  { value: "devops", label: "DevOps" },
  { value: "agile", label: "Agile Methodology" },
  { value: "uxui", label: "UX/UI Design" },
  { value: "blockchain", label: "Blockchain" },
];
